version: '3.3'

services:
  client:
    build:
      context: client
      dockerfile: Dockerfile
    container_name: client
    restart: always
    ports:
      - 80:80
      # external:internal
    depends_on:
      - server-service

  server-service:
    build:
      context: server
      dockerfile: Dockerfile
    container_name: server-container
    restart: always
    ports:
    - 8000:8000
    env_file:
    - ./server/.env.dev
    command: uvicorn src.api:app --host 0.0.0.0
    depends_on:
      - db-service

  db-service:
    image: mariadb:11
    restart: always
    container_name: db-container
    environment:
      MARIADB_DATABASE: db
      MARIADB_USER: user
      MARIADB_PASSWORD: password
      MARIADB_ROOT_PASSWORD: rootpassword
    ports:
      - 3306:3306
    volumes:
      - ./server/init.sql:/docker-entrypoint-initdb.d/init.sql