version: '3.3'

services:
  client:
    build:
      context: client
      dockerfile: Dockerfile.dev
    container_name: client
    restart: always
    volumes:
      - ./client:/app
      - /app/node_modules
    ports:
      - 8080:5173
      # external:internal
    command: yarn dev

  server:
    build:
      context: server
      dockerfile: Dockerfile.dev
    container_name: server
    restart: always
    volumes:
      - ./server:/app
    ports:
      - 8000:8000
    # localhost:8000
    env_file:
    - ./server/.env.dev
    command: uvicorn src.api:app --host 0.0.0.0 --reload
    depends_on:
      - db-service

  db-service:
    image: mariadb:11
    restart: always
    container_name: db-container
    environment:
      MARIADB_DATABASE: db
      MARIADB_USER: user
      MARIADB_PASSWORD: password
      MARIADB_ROOT_PASSWORD: rootpassword
    ports:
      - 3306:3306
    volumes:
      - ./server/init.sql:/docker-entrypoint-initdb.d/init.sql