CREATE DATABASE IF NOT EXISTS `db`
DEFAULT CHARACTER SET utf8
DEFAULT COLLATE utf8_unicode_ci;

USE db;

CREATE TABLE IF NOT EXISTS greetings (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(255) NOT NULL UNIQUE
);

INSERT INTO greetings (username) VALUES ('World')